El primer paso es desacargar las cartolas y exienten 2 principalmente

In [3]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd
import math

# Lee el archivo Excel
df2 = pd.read_excel('cartola_parte_3.xls')

# Define una función para eliminar filas y columnas según el contador de iteración
def eliminar_filas_columnas(df2,columnas_a_eliminar):
    for i, fila in enumerate(df2.index):
        if i in columnas_a_eliminar:
            df2 = df2.drop(index=fila)
    return df2

# Define una función para recorrer el DataFrame y mostrar el contenido de cada celda
max_row_to_delete= list()
def iterar_filas_columnas(df2):
    for i, fila in enumerate(df2.index):
        lista_valores_fila = list()
        for j, columna in enumerate(df2.columns):
            contenido_celda = df2.loc[fila, columna]
            lista_valores_fila.append(contenido_celda)
        if  all(pd.isna(elemento) for elemento in lista_valores_fila):
            max_row_to_delete.append(fila)
            print (f'fila {fila} se puede eliminar')
        else:
            print (f'fila {fila} tiene valores , No se puede eliminar')
            print (lista_valores_fila)
    return   max_row_to_delete          
filas_a_eliminar = iterar_filas_columnas(df2)
filas_a_eliminar

fila 0 se puede eliminar
fila 1 se puede eliminar
fila 2 se puede eliminar
fila 3 se puede eliminar
fila 4 se puede eliminar
fila 5 se puede eliminar
fila 6 tiene valores , No se puede eliminar
[nan, 'Sr(a): ', 'Cristobal Andres Labe Sanchez', nan, nan, nan, nan]
fila 7 tiene valores , No se puede eliminar
[nan, 'Rut:', '19.831.394-7', nan, nan, nan, nan]
fila 8 tiene valores , No se puede eliminar
[nan, 'Cuenta:', '00-288-02551-02', nan, nan, nan, nan]
fila 9 tiene valores , No se puede eliminar
[nan, 'Moneda:', 'Pesos Chilenos (CLP)', nan, nan, nan, nan]
fila 10 se puede eliminar
fila 11 se puede eliminar
fila 12 tiene valores , No se puede eliminar
[nan, 'Saldos al 19/04/2024 21:39 Hrs.', nan, nan, nan, nan, nan]
fila 13 se puede eliminar
fila 14 se puede eliminar
fila 15 tiene valores , No se puede eliminar
[nan, 'Saldo Disponible', 'Saldo Contable', 'Retenciones 24 Hrs.', 'Retenciones 48 Hrs.', nan, nan]
fila 16 tiene valores , No se puede eliminar
[nan, 85782, 85782, 0, 0, nan, nan]
fila 17 se puede eliminar
fila 18 se puede eliminar
fila 19 tiene valores , No se puede eliminar
[nan, 'Total Cargos', 'Total Abonos', 'Línea de Crédito', nan, nan, nan]
fila 20 tiene valores , No se puede eliminar
[nan, 1345592, 9200, 1000000, nan, nan, nan]
fila 21 se puede eliminar
fila 22 se puede eliminar
fila 23 se puede eliminar
fila 24 tiene valores , No se puede eliminar
[nan, 'Movimientos al 19/04/2024', nan, nan, nan, nan, nan]
fila 25 tiene valores , No se puede eliminar
[nan, 'Fecha', 'Descripción', 'Canal o Sucursal', 'Cargos (CLP)', 'Abonos (CLP)', 'Saldo (CLP)']
fila 26 tiene valores , No se puede eliminar
[nan, '19/04/2024', 'Pago:carlos Andres Dia', 'Of. El Belloto Op.', 3200, nan, 85782]
fila 27 tiene valores , No se puede eliminar
[nan, '19/04/2024', 'Pago:express Pd Valdiv', 'Of. El Belloto Op.', 10810, nan, 88982]
fila 28 tiene valores , No se puede eliminar
[nan, '19/04/2024', 'Pago:dulce Pola Spa', 'Of. El Belloto Op.', 1000, nan, 99792]
fila 29 tiene valores , No se puede eliminar
[nan, '18/04/2024', 'Pago:wei', 'Of. El Belloto Op.', 45908, nan, 104272]
fila 30 tiene valores , No se puede eliminar
[nan, '17/04/2024', 'Pago:metrogas Metrogas', 'Of. El Belloto Op.', 8137, nan, 150180]
fila 31 tiene valores , No se puede eliminar
[nan, '17/04/2024', 'Traspaso De:Hans Cristian Jeria Diaz', 'Internet', nan, 9200, 158317]
fila 32 tiene valores , No se puede eliminar
[nan, '17/04/2024', 'Pago:mt Aut Los Leones', 'Of. El Belloto Op.', 10000, nan, 149117]
fila 33 tiene valores , No se puede eliminar
[nan, '15/04/2024', 'Pago:jose Jara', 'Of. El Belloto Op.', 2300, nan, 159117]
fila 34 tiene valores , No se puede eliminar
[nan, '15/04/2024', 'Pago:kelos San Joaquin', 'Of. El Belloto Op.', 10131, nan, 161417]
fila 35 tiene valores , No se puede eliminar
[nan, '12/04/2024', 'Pago:jmg Gastronomia L', 'Of. El Belloto Op.', 56705, nan, 171548]
fila 36 tiene valores , No se puede eliminar
[nan, '11/04/2024', 'Pago:kioskos Kfc San J', 'Of. El Belloto Op.', 5200, nan, 228253]
fila 37 tiene valores , No se puede eliminar
[nan, '10/04/2024', 'Cargo Seguro Proteccion Bancaria', 'Oficina Central', 2973, nan, 233453]
fila 38 tiene valores , No se puede eliminar
[nan, '10/04/2024', 'Pago:express Irarrazav', 'Of. El Belloto Op.', 2530, nan, 236426]
fila 39 tiene valores , No se puede eliminar
[nan, '10/04/2024', 'Pago:pomona Spa', 'Of. El Belloto Op.', 3800, nan, 238956]
fila 40 tiene valores , No se puede eliminar
[nan, '09/04/2024', 'Traspaso A:Ana Carolina Santander', 'Internet', 151600, nan, 242756]
fila 41 tiene valores , No se puede eliminar
[nan, '09/04/2024', 'Pago:merpago*autoservi', 'Of. El Belloto Op.', 2200, nan, 394356]
fila 42 tiene valores , No se puede eliminar
[nan, '09/04/2024', 'Pago:cinepolis La Rein', 'Of. El Belloto Op.', 5600, nan, 396556]
fila 43 tiene valores , No se puede eliminar
[nan, '09/04/2024', 'Pago:maxik', 'Of. El Belloto Op.', 2580, nan, 402156]
fila 44 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Traspaso A:Khipu Clbs B', 'Internet', 15229, nan, 404736]
fila 45 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Traspaso A:Khipu Clbs B', 'Internet', 6913, nan, 419965]
fila 46 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Giro Cajero Automatico             *', 'Of. El Belloto Op.', 10000, nan, 426878]
fila 47 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:wendy S Vespucio', 'Of. El Belloto Op.', 7190, nan, 436878]
fila 48 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:merpago*maria Ver', 'Of. El Belloto Op.', 6000, nan, 444068]
fila 49 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:easy Florida Cent', 'Of. El Belloto Op.', 10990, nan, 450068]
fila 50 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:florida Center', 'Of. El Belloto Op.', 11290, nan, 461058]
fila 51 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:tommy Beans Flori', 'Of. El Belloto Op.', 7490, nan, 472348]
fila 52 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Traspaso A:Aguas Andinas', 'Internet', 1750, nan, 479838]
fila 53 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Recaudacion Y Pagos De Servicios   *', 'Oficina Central', 29835, nan, 481588]
fila 54 tiene valores , No se puede eliminar
[nan, '08/04/2024', 'Pago:sumup * Aulamusic', 'Of. El Belloto Op.', 7500, nan, 511423]
fila 55 tiene valores , No se puede eliminar
[nan, '05/04/2024', 'Traspaso A:Cristobal Labe', 'Internet', 8000, nan, 518923]
fila 56 tiene valores , No se puede eliminar
[nan, '05/04/2024', 'Traspaso A:Ricardo Huilipan', 'Internet', 16995, nan, 526923]
fila 57 tiene valores , No se puede eliminar
[nan, '05/04/2024', 'Traspaso A:Dulce Pola Spa', 'Internet', 2400, nan, 543918]
fila 58 tiene valores , No se puede eliminar
[nan, '04/04/2024', 'Pago:studio Lions', 'Of. El Belloto Op.', 12000, nan, 546318]
fila 59 tiene valores , No se puede eliminar
[nan, '04/04/2024', 'Pago:merpago*ruta Del', 'Of. El Belloto Op.', 3900, nan, 558318]
fila 60 tiene valores , No se puede eliminar
[nan, '03/04/2024', 'Pago:el Container', 'Of. El Belloto Op.', 51892, nan, 562218]
fila 61 tiene valores , No se puede eliminar
[nan, '01/04/2024', 'Traspaso A:Fintual Agf S.a.', 'Internet', 350000, nan, 614110]
fila 62 tiene valores , No se puede eliminar
[nan, '01/04/2024', 'Cargo Por Pago Tc', 'Internet', 371023, nan, 964110]
fila 63 tiene valores , No se puede eliminar
[nan, '01/04/2024', 'Traspaso A:Ana Carolina Santander', 'Internet', 70521, nan, 1335133]
fila 64 tiene valores , No se puede eliminar
[nan, '01/04/2024', 'Pago:mt Aut Nunoa L6', 'Of. El Belloto Op.', 10000, nan, 1405654]
fila 65 tiene valores , No se puede eliminar
[nan, '01/04/2024', 'Pago:sumup * Aulamusic', 'Of. El Belloto Op.', 10000, nan, 1415654]
fila 66 se puede eliminar
fila 67 se puede eliminar
fila 68 se puede eliminar
fila 69 se puede eliminar
fila 70 se puede eliminar
fila 71 se puede eliminar
fila 72 tiene valores , No se puede eliminar
[nan, 'Infórmate sobre la garantía estatal de los depósitos en tu banco o en www.sbif.cl.\n©2023 Banco de Chile. Todos los Derechos Reserados.', nan, nan, nan, nan, nan]

[0, 1, 2, 3, 4, 5, 10, 11, 13, 14, 17, 18, 21, 22, 23, 66, 67, 68, 69, 70, 71]

In [ ]:
df2.drop(filas_a_eliminar,inplace=True)

In [ ]:
for columna in df2.columns:
    # Verifica si todos los valores en la columna son nulos
    if df2[columna].isnull().all():
        # Elimina la columna si todos los valores son nulos
        df2.drop(columna, axis=1, inplace=True)
df2.reset_index(drop=True,inplace=True)  # resetear índice de filas
df2.columns = range(df2.shape[1])  # resetear índice de columnas
df2

,0,1,2,3,4,5
0,Sr(a):,Cristobal Andres Labe Sanchez,NaN,NaN,NaN,NaN
1,Rut:,19.831.394-7,NaN,NaN,NaN,NaN
2,Cuenta:,00-288-02551-02,NaN,NaN,NaN,NaN
3,Moneda:,Pesos Chilenos (CLP),NaN,NaN,NaN,NaN
4,Saldos al 19/04/2024 21:39 Hrs.,NaN,NaN,NaN,NaN,NaN
5,Saldo Disponible,Saldo Contable,Retenciones 24 Hrs.,Retenciones 48 Hrs.,NaN,NaN
6,85782,85782,0,0,NaN,NaN
7,Total Cargos,Total Abonos,Línea de Crédito,NaN,NaN,NaN
8,1345592,9200,1000000,NaN,NaN,NaN
9,Movimientos al 19/04/2024,NaN,NaN,NaN,NaN,NaN
10,Fecha,Descripción,Canal o Sucursal,Cargos (CLP),Abonos (CLP),Saldo (CLP)
11,19/04/2024,Pago:carlos Andres Dia,Of. El Belloto Op.,3200,NaN,85782
12,19/04/2024,Pago:express Pd Valdiv,Of. El Belloto Op.,10810,NaN,88982
13,19/04/2024,Pago:dulce Pola Spa,Of. El Belloto Op.,1000,NaN,99792
14,18/04/2024,Pago:wei,Of. El Belloto Op.,45908,NaN,104272
15,17/04/2024,Pago:metrogas Metrogas,Of. El Belloto Op.,8137,NaN,150180
16,17/04/2024,Traspaso De:Hans Cristian Jeria Diaz,Internet,NaN,9200,158317
17,17/04/2024,Pago:mt Aut Los Leones,Of. El Belloto Op.,10000,NaN,149117
18,15/04/2024,Pago:jose Jara,Of. El Belloto Op.,2300,NaN,159117
19,15/04/2024,Pago:kelos San Joaquin,Of. El Belloto Op.,10131,NaN,161417
20,12/04/2024,Pago:jmg Gastronomia L,Of. El Belloto Op.,56705,NaN,171548
21,11/04/2024,Pago:kioskos Kfc San J,Of. El Belloto Op.,5200,NaN,228253
22,10/04/2024,Cargo Seguro Proteccion Bancaria,Oficina Central,2973,NaN,233453
23,10/04/2024,Pago:express Irarrazav,Of. El Belloto Op.,2530,NaN,236426
24,10/04/2024,Pago:pomona Spa,Of. El Belloto Op.,3800,NaN,238956
25,09/04/2024,Traspaso A:Ana Carolina Santander,Internet,151600,NaN,242756
26,09/04/2024,Pago:merpago*autoservi,Of. El Belloto Op.,2200,NaN,394356
27,09/04/2024,Pago:cinepolis La Rein,Of. El Belloto Op.,5600,NaN,396556
28,09/04/2024,Pago:maxik,Of. El Belloto Op.,2580,NaN,402156
29,08/04/2024,Traspaso A:Khipu Clbs B,Internet,15229,NaN,404736
30,08/04/2024,Traspaso A:Khipu Clbs B,Internet,6913,NaN,419965
31,08/04/2024,Giro Cajero Automatico *,Of. El Belloto Op.,10000,NaN,426878
32,08/04/2024,Pago:wendy S Vespucio,Of. El Belloto Op.,7190,NaN,436878
33,08/04/2024,Pago:merpago*maria Ver,Of. El Belloto Op.,6000,NaN,444068
34,08/04/2024,Pago:easy Florida Cent,Of. El Belloto Op.,10990,NaN,450068
35,08/04/2024,Pago:florida Center,Of. El Belloto Op.,11290,NaN,461058
36,08/04/2024,Pago:tommy Beans Flori,Of. El Belloto Op.,7490,NaN,472348
37,08/04/2024,Traspaso A:Aguas Andinas,Internet,1750,NaN,479838
38,08/04/2024,Recaudacion Y Pagos De Servicios *,Oficina Central,29835,NaN,481588
39,08/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,7500,NaN,511423
40,05/04/2024,Traspaso A:Cristobal Labe,Internet,8000,NaN,518923
41,05/04/2024,Traspaso A:Ricardo Huilipan,Internet,16995,NaN,526923
42,05/04/2024,Traspaso A:Dulce Pola Spa,Internet,2400,NaN,543918
43,04/04/2024,Pago:studio Lions,Of. El Belloto Op.,12000,NaN,546318
44,04/04/2024,Pago:merpago*ruta Del,Of. El Belloto Op.,3900,NaN,558318
45,03/04/2024,Pago:el Container,Of. El Belloto Op.,51892,NaN,562218
46,01/04/2024,Traspaso A:Fintual Agf S.a.,Internet,350000,NaN,614110
47,01/04/2024,Cargo Por Pago Tc,Internet,371023,NaN,964110
48,01/04/2024,Traspaso A:Ana Carolina Santander,Internet,70521,NaN,1335133
49,01/04/2024,Pago:mt Aut Nunoa L6,Of. El Belloto Op.,10000,NaN,1405654
50,01/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,10000,NaN,1415654
51,Infórmate sobre la garantía estatal de los dep...,NaN,NaN,NaN,NaN,NaN

In [ ]:
headers_values = []
expected_headers = ['Fecha', 'Descripción', 'Canal o Sucursal', 'Cargos (CLP)', 'Abonos (CLP)', 'Saldo (CLP)']
deleted_rows_not_table = 0 ## almacena hasta donde se va a eliminar datos que no son propios de la tabla de datos

for indice, fila in df2.iterrows():
    valores_fila = fila.tolist()
    # Comparación insensible a mayúsculas y minúsculas y sin espacios adicionales
    valores_fila_strip = [valor.strip().lower() if isinstance(valor, str) else valor for valor in valores_fila]
    if valores_fila_strip == [header.lower() for header in expected_headers]:
        headers_values.append(valores_fila)
        deleted_rows_not_table = indice


print(headers_values)
print (deleted_rows_not_table)
df2.drop(list(range(deleted_rows_not_table)),inplace=True)
df2

[['Fecha', 'Descripción', 'Canal o Sucursal', 'Cargos (CLP)', 'Abonos (CLP)', 'Saldo (CLP)']]
10

,0,1,2,3,4,5
10,Fecha,Descripción,Canal o Sucursal,Cargos (CLP),Abonos (CLP),Saldo (CLP)
11,19/04/2024,Pago:carlos Andres Dia,Of. El Belloto Op.,3200,NaN,85782
12,19/04/2024,Pago:express Pd Valdiv,Of. El Belloto Op.,10810,NaN,88982
13,19/04/2024,Pago:dulce Pola Spa,Of. El Belloto Op.,1000,NaN,99792
14,18/04/2024,Pago:wei,Of. El Belloto Op.,45908,NaN,104272
15,17/04/2024,Pago:metrogas Metrogas,Of. El Belloto Op.,8137,NaN,150180
16,17/04/2024,Traspaso De:Hans Cristian Jeria Diaz,Internet,NaN,9200,158317
17,17/04/2024,Pago:mt Aut Los Leones,Of. El Belloto Op.,10000,NaN,149117
18,15/04/2024,Pago:jose Jara,Of. El Belloto Op.,2300,NaN,159117
19,15/04/2024,Pago:kelos San Joaquin,Of. El Belloto Op.,10131,NaN,161417
20,12/04/2024,Pago:jmg Gastronomia L,Of. El Belloto Op.,56705,NaN,171548
21,11/04/2024,Pago:kioskos Kfc San J,Of. El Belloto Op.,5200,NaN,228253
22,10/04/2024,Cargo Seguro Proteccion Bancaria,Oficina Central,2973,NaN,233453
23,10/04/2024,Pago:express Irarrazav,Of. El Belloto Op.,2530,NaN,236426
24,10/04/2024,Pago:pomona Spa,Of. El Belloto Op.,3800,NaN,238956
25,09/04/2024,Traspaso A:Ana Carolina Santander,Internet,151600,NaN,242756
26,09/04/2024,Pago:merpago*autoservi,Of. El Belloto Op.,2200,NaN,394356
27,09/04/2024,Pago:cinepolis La Rein,Of. El Belloto Op.,5600,NaN,396556
28,09/04/2024,Pago:maxik,Of. El Belloto Op.,2580,NaN,402156
29,08/04/2024,Traspaso A:Khipu Clbs B,Internet,15229,NaN,404736
30,08/04/2024,Traspaso A:Khipu Clbs B,Internet,6913,NaN,419965
31,08/04/2024,Giro Cajero Automatico *,Of. El Belloto Op.,10000,NaN,426878
32,08/04/2024,Pago:wendy S Vespucio,Of. El Belloto Op.,7190,NaN,436878
33,08/04/2024,Pago:merpago*maria Ver,Of. El Belloto Op.,6000,NaN,444068
34,08/04/2024,Pago:easy Florida Cent,Of. El Belloto Op.,10990,NaN,450068
35,08/04/2024,Pago:florida Center,Of. El Belloto Op.,11290,NaN,461058
36,08/04/2024,Pago:tommy Beans Flori,Of. El Belloto Op.,7490,NaN,472348
37,08/04/2024,Traspaso A:Aguas Andinas,Internet,1750,NaN,479838
38,08/04/2024,Recaudacion Y Pagos De Servicios *,Oficina Central,29835,NaN,481588
39,08/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,7500,NaN,511423
40,05/04/2024,Traspaso A:Cristobal Labe,Internet,8000,NaN,518923
41,05/04/2024,Traspaso A:Ricardo Huilipan,Internet,16995,NaN,526923
42,05/04/2024,Traspaso A:Dulce Pola Spa,Internet,2400,NaN,543918
43,04/04/2024,Pago:studio Lions,Of. El Belloto Op.,12000,NaN,546318
44,04/04/2024,Pago:merpago*ruta Del,Of. El Belloto Op.,3900,NaN,558318
45,03/04/2024,Pago:el Container,Of. El Belloto Op.,51892,NaN,562218
46,01/04/2024,Traspaso A:Fintual Agf S.a.,Internet,350000,NaN,614110
47,01/04/2024,Cargo Por Pago Tc,Internet,371023,NaN,964110
48,01/04/2024,Traspaso A:Ana Carolina Santander,Internet,70521,NaN,1335133
49,01/04/2024,Pago:mt Aut Nunoa L6,Of. El Belloto Op.,10000,NaN,1405654
50,01/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,10000,NaN,1415654
51,Infórmate sobre la garantía estatal de los dep...,NaN,NaN,NaN,NaN,NaN

In [ ]:
nuevos_encabezados = df2.iloc[0] 
df2.rename(columns=nuevos_encabezados,inplace = True)  # Establecer los nuevos encabezados de columna
df2.drop(df2.index[0], inplace=True)
df2.reset_index(drop=True,inplace=True)
df2

,Fecha,Descripción,Canal o Sucursal,Cargos (CLP),Abonos (CLP),Saldo (CLP)
0,19/04/2024,Pago:carlos Andres Dia,Of. El Belloto Op.,3200,NaN,85782
1,19/04/2024,Pago:express Pd Valdiv,Of. El Belloto Op.,10810,NaN,88982
2,19/04/2024,Pago:dulce Pola Spa,Of. El Belloto Op.,1000,NaN,99792
3,18/04/2024,Pago:wei,Of. El Belloto Op.,45908,NaN,104272
4,17/04/2024,Pago:metrogas Metrogas,Of. El Belloto Op.,8137,NaN,150180
5,17/04/2024,Traspaso De:Hans Cristian Jeria Diaz,Internet,NaN,9200,158317
6,17/04/2024,Pago:mt Aut Los Leones,Of. El Belloto Op.,10000,NaN,149117
7,15/04/2024,Pago:jose Jara,Of. El Belloto Op.,2300,NaN,159117
8,15/04/2024,Pago:kelos San Joaquin,Of. El Belloto Op.,10131,NaN,161417
9,12/04/2024,Pago:jmg Gastronomia L,Of. El Belloto Op.,56705,NaN,171548
10,11/04/2024,Pago:kioskos Kfc San J,Of. El Belloto Op.,5200,NaN,228253
11,10/04/2024,Cargo Seguro Proteccion Bancaria,Oficina Central,2973,NaN,233453
12,10/04/2024,Pago:express Irarrazav,Of. El Belloto Op.,2530,NaN,236426
13,10/04/2024,Pago:pomona Spa,Of. El Belloto Op.,3800,NaN,238956
14,09/04/2024,Traspaso A:Ana Carolina Santander,Internet,151600,NaN,242756
15,09/04/2024,Pago:merpago*autoservi,Of. El Belloto Op.,2200,NaN,394356
16,09/04/2024,Pago:cinepolis La Rein,Of. El Belloto Op.,5600,NaN,396556
17,09/04/2024,Pago:maxik,Of. El Belloto Op.,2580,NaN,402156
18,08/04/2024,Traspaso A:Khipu Clbs B,Internet,15229,NaN,404736
19,08/04/2024,Traspaso A:Khipu Clbs B,Internet,6913,NaN,419965
20,08/04/2024,Giro Cajero Automatico *,Of. El Belloto Op.,10000,NaN,426878
21,08/04/2024,Pago:wendy S Vespucio,Of. El Belloto Op.,7190,NaN,436878
22,08/04/2024,Pago:merpago*maria Ver,Of. El Belloto Op.,6000,NaN,444068
23,08/04/2024,Pago:easy Florida Cent,Of. El Belloto Op.,10990,NaN,450068
24,08/04/2024,Pago:florida Center,Of. El Belloto Op.,11290,NaN,461058
25,08/04/2024,Pago:tommy Beans Flori,Of. El Belloto Op.,7490,NaN,472348
26,08/04/2024,Traspaso A:Aguas Andinas,Internet,1750,NaN,479838
27,08/04/2024,Recaudacion Y Pagos De Servicios *,Oficina Central,29835,NaN,481588
28,08/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,7500,NaN,511423
29,05/04/2024,Traspaso A:Cristobal Labe,Internet,8000,NaN,518923
30,05/04/2024,Traspaso A:Ricardo Huilipan,Internet,16995,NaN,526923
31,05/04/2024,Traspaso A:Dulce Pola Spa,Internet,2400,NaN,543918
32,04/04/2024,Pago:studio Lions,Of. El Belloto Op.,12000,NaN,546318
33,04/04/2024,Pago:merpago*ruta Del,Of. El Belloto Op.,3900,NaN,558318
34,03/04/2024,Pago:el Container,Of. El Belloto Op.,51892,NaN,562218
35,01/04/2024,Traspaso A:Fintual Agf S.a.,Internet,350000,NaN,614110
36,01/04/2024,Cargo Por Pago Tc,Internet,371023,NaN,964110
37,01/04/2024,Traspaso A:Ana Carolina Santander,Internet,70521,NaN,1335133
38,01/04/2024,Pago:mt Aut Nunoa L6,Of. El Belloto Op.,10000,NaN,1405654
39,01/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,10000,NaN,1415654
40,Infórmate sobre la garantía estatal de los dep...,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2.drop(df2.index[-1], inplace=True) ## eliminar la ultima fila innecesaria de datos

In [ ]:
df2

,Fecha,Descripción,Canal o Sucursal,Cargos (CLP),Abonos (CLP),Saldo (CLP)
0,19/04/2024,Pago:carlos Andres Dia,Of. El Belloto Op.,3200,NaN,85782
1,19/04/2024,Pago:express Pd Valdiv,Of. El Belloto Op.,10810,NaN,88982
2,19/04/2024,Pago:dulce Pola Spa,Of. El Belloto Op.,1000,NaN,99792
3,18/04/2024,Pago:wei,Of. El Belloto Op.,45908,NaN,104272
4,17/04/2024,Pago:metrogas Metrogas,Of. El Belloto Op.,8137,NaN,150180
5,17/04/2024,Traspaso De:Hans Cristian Jeria Diaz,Internet,NaN,9200,158317
6,17/04/2024,Pago:mt Aut Los Leones,Of. El Belloto Op.,10000,NaN,149117
7,15/04/2024,Pago:jose Jara,Of. El Belloto Op.,2300,NaN,159117
8,15/04/2024,Pago:kelos San Joaquin,Of. El Belloto Op.,10131,NaN,161417
9,12/04/2024,Pago:jmg Gastronomia L,Of. El Belloto Op.,56705,NaN,171548
10,11/04/2024,Pago:kioskos Kfc San J,Of. El Belloto Op.,5200,NaN,228253
11,10/04/2024,Cargo Seguro Proteccion Bancaria,Oficina Central,2973,NaN,233453
12,10/04/2024,Pago:express Irarrazav,Of. El Belloto Op.,2530,NaN,236426
13,10/04/2024,Pago:pomona Spa,Of. El Belloto Op.,3800,NaN,238956
14,09/04/2024,Traspaso A:Ana Carolina Santander,Internet,151600,NaN,242756
15,09/04/2024,Pago:merpago*autoservi,Of. El Belloto Op.,2200,NaN,394356
16,09/04/2024,Pago:cinepolis La Rein,Of. El Belloto Op.,5600,NaN,396556
17,09/04/2024,Pago:maxik,Of. El Belloto Op.,2580,NaN,402156
18,08/04/2024,Traspaso A:Khipu Clbs B,Internet,15229,NaN,404736
19,08/04/2024,Traspaso A:Khipu Clbs B,Internet,6913,NaN,419965
20,08/04/2024,Giro Cajero Automatico *,Of. El Belloto Op.,10000,NaN,426878
21,08/04/2024,Pago:wendy S Vespucio,Of. El Belloto Op.,7190,NaN,436878
22,08/04/2024,Pago:merpago*maria Ver,Of. El Belloto Op.,6000,NaN,444068
23,08/04/2024,Pago:easy Florida Cent,Of. El Belloto Op.,10990,NaN,450068
24,08/04/2024,Pago:florida Center,Of. El Belloto Op.,11290,NaN,461058
25,08/04/2024,Pago:tommy Beans Flori,Of. El Belloto Op.,7490,NaN,472348
26,08/04/2024,Traspaso A:Aguas Andinas,Internet,1750,NaN,479838
27,08/04/2024,Recaudacion Y Pagos De Servicios *,Oficina Central,29835,NaN,481588
28,08/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,7500,NaN,511423
29,05/04/2024,Traspaso A:Cristobal Labe,Internet,8000,NaN,518923
30,05/04/2024,Traspaso A:Ricardo Huilipan,Internet,16995,NaN,526923
31,05/04/2024,Traspaso A:Dulce Pola Spa,Internet,2400,NaN,543918
32,04/04/2024,Pago:studio Lions,Of. El Belloto Op.,12000,NaN,546318
33,04/04/2024,Pago:merpago*ruta Del,Of. El Belloto Op.,3900,NaN,558318
34,03/04/2024,Pago:el Container,Of. El Belloto Op.,51892,NaN,562218
35,01/04/2024,Traspaso A:Fintual Agf S.a.,Internet,350000,NaN,614110
36,01/04/2024,Cargo Por Pago Tc,Internet,371023,NaN,964110
37,01/04/2024,Traspaso A:Ana Carolina Santander,Internet,70521,NaN,1335133
38,01/04/2024,Pago:mt Aut Nunoa L6,Of. El Belloto Op.,10000,NaN,1405654
39,01/04/2024,Pago:sumup * Aulamusic,Of. El Belloto Op.,10000,NaN,1415654